common: &common
  adapter: postgresql
  username: Skerou

development:
  <<: *common
  database: residence_goldwyn_dev

test:
  <<: *common
  database: residence_goldwyn_test

production:
  <<: *common
  database: residence_goldwyn_prod